title: Michal Orman's Blog
email: michal.orman@gmail.com
description: >
  Blog about the art of software development.
baseurl: ""
url: "http://michalorman.com"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
permalink:  /:year/:month/:title
paginate: 7
